# Generated by Django 4.0 on 2024-05-15 08:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_room_created_by_alter_profile_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='chat.profile'),
            preserve_default=False,
        ),
    ]
